# Generated by Django 3.1.5 on 2021-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('message', models.TextField()),
                ('code', models.TextField()),
                ('status', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
